<script>
    document.addEventListener('DOMContentLoaded', () => {
        const translations = {
            arabic: {
                welcome: 'مرحبا',
                select_language: 'اختر اللغة',
                arabic :  'العربية',
                english : 'الإنجليزية',
                german : 'الألمانية',
                china : 'الصينية',
                french : 'الفرنسية',
                india : 'الهندية',
                myaccount : 'حسابي',
                changepassword : 'تغيير كلمة المرور',
                logout : 'تسجيل الخروج',
                home : 'الصفحة الرئيسية',
                news : 'الأخبار',
                wallet : 'المحفظة',
                streams : 'البثوث',
                support : 'الدعم',
                report : 'الإبلاغ',
                help : 'المساعدة',
                main : 'الرئيسية',
                sendreport : 'إرسال تقرير',
                subject : 'الموضوع',
                selectsubject : 'اختر الموضوع',
                details : 'التفاصيل',
                try_to_include_all_details : 'حاول تضمين جميع التفاصيل...',
                attachfile : 'إرفاق ملف',
                cancel : 'إلغاء',
                submit : 'إرسال',
                popularqa : 'الأسئلة والأجوبة الشائعة',
                browse_all_articles : 'تصفح جميع المقالات',
                noblogsfound : 'لم يتم العثور على مدونات.',
                updateaccount : 'تحديث الحساب',
                image : 'صورة',
                username : 'اسم المستخدم',
                nickname : 'اللقب',
                email : 'البريد الإلكتروني',
                update : 'تحديث',
                updatepassword : 'تحديث كلمة المرور',
                currentpassword : 'كلمة المرور الحالية',
                newpassword : 'كلمة المرور الجديدة',
                change : 'تغيير',
                recomndedevent : 'الأحداث الموصى بها',
                newsarchive : 'أرشيف الأخبار',
                ourcommunities : 'مجتمعاتنا',
                downloadnow : 'حمل الآن',
                categories : 'التصنيفات',
                yourwallet : 'محفظتك',
                yourjwel : 'مجوهراتك',
                yourcoins : 'عملاتك',
                buynow : 'اشتري الآن',
                ourstreams : 'بثوثنا',
                addstream : 'إضافة بث',
                all : 'الكل',
                English : 'الإنجليزية',
                Arabic : 'العربية',
                Germany : 'الألمانية',
                China : 'الصينية',
                India : 'الهندية',
                French : 'الفرنسية',
                admin_dashboard : 'لوحة التحكم',
                no_news_available : 'لا توجد أخبار متاحة.',
                add_stream : 'إضافة بث',
                title : 'العنوان',
                url : 'الرابط',
                language : 'اللغة',
                select_language : 'اختر اللغة',
                image : 'الصورة',
                add : 'إضافة',
                username : 'اسم المستخدم',
                nickname : 'اللقب',
                email : 'البريد الإلكتروني',
                ip : 'IP',
                active : 'نشط',
                actions : 'الإجراءات',
                edit_user : 'تحرير المستخدم',
                created_at : 'تم الإنشاء في',
                user_details : 'تفاصيل المستخدم',
                users : 'المستخدمين',
                admins : 'المشرفين',
                blogs : 'المدونات',
                charges : 'الرسوم',
                communities : 'المجتمعات',
                events : 'الأحداث',
                add_admin : 'إضافة مشرف',
                edit_admin : 'تحرير المشرف',


            },
            english: {
                welcome: 'Welcome',
                select_language: 'Select Language',
                arabic :  'Arabic',
                english : 'English',
                german : 'German',
                china : 'China',
                french : 'French',
                india : 'India',
                myaccount : 'My account',
                changepassword : 'Change Password',
                logout : 'Log Out',
                home : 'Home',
                news : 'News',
                wallet : 'Wallet',
                streams : 'Streams',
                support : 'Support',
                report : 'Report',
                help : 'Help',
                main : 'Main',
                sendreport : 'Send Report',
                subject : 'Subject',
                selectsubject : 'Select Subject',
                details : 'Details',
                try_to_include_all_details : 'Try to include all details...',
                attachfile : 'Attach File',
                cancel : 'Cancel',
                submit : 'Submit',
                popularqa : 'Popular Q&A',
                browse_all_articles : 'Browse all articles',
                noblogsfound : 'No blogs found.',
                updateaccount : 'Update Account',
                image : 'Image',
                username : 'User Name',
                nickname : 'Nick Name',
                email : 'Email',
                update : 'Update',  
                updatepassword : 'Update Password',
                currentpassword : 'Current Password',
                newpassword : 'New Password',
                change : 'Change',
                recomndedevent : 'Recommended Events',
                newsarchive : 'News Archive',
                ourcommunities : 'Our Communities',
                downloadnow : 'Download Now',
                categories : 'Categories',
                yourwallet : 'Your Wallet',
                yourjwel : 'Your Jwel',
                yourcoins : 'Your Coins',
                buynow : 'Buy Now',
                ourstreams : 'Our Streams',
                addstream : 'Add Stream',
                all : 'All',
                English : 'English',
                Arabic : 'Arabic',
                Germany : 'Germany',
                China : 'China',
                India : 'India',
                French : 'French',
                admin_dashboard : 'Admin Dashboard',
                no_news_available : 'No news available.',
                add_stream : 'Add Stream',
                title : 'Title',
                url : 'URL',
                language : 'Language',
                select_language : 'Select Language',
                image : 'Image',
                add : 'Add',
                username : 'User Name',
                nickname : 'Nick Name',
                email : 'Email',
                ip : 'IP',
                active : 'Active',
                actions : 'Actions',
                edit_user : 'Edit User',
                user_details : 'User Details',
                created_at : 'Created At',
                users : 'Users',
                admins : 'Admins',
                blogs : 'Blogs',
                charges : 'Charges',
                communities : 'Communities',
                events : 'Events',
                add_admin : 'Add Admin',
                edit_admin : 'Edit Admin',
            },
            german: {
                welcome: 'Willkommen',
                select_language: 'Sprache auswählen',
                arabic : 'Arabisch',
                english : 'Englisch',
                german : 'Deutsch',
                china : 'Chinesisch',
                french : 'Französisch',
                india : 'Indisch',
                myaccount : 'Mein Konto',
                changepassword : 'Pass ändern',
                logout : 'Ausloggen',
                home : 'Zuhause',
                news : 'Nachrichten',
                wallet : 'Brieftasche',
                streams : 'Ströme',
                support : 'Unterstützung',
                report : 'Bericht',
                help : 'Hilfe',
                main : 'Haupt',
                sendreport : 'Bericht senden',
                subject : 'Gegenstand',
                selectsubject : 'Wählen Sie ein Thema',
                details : 'Einzelheiten',
                try_to_include_all_details : 'Versuchen Sie, alle Details einzubeziehen...',
                attachfile : 'Datei anhängen',
                cancel : 'Stornieren',
                submit : 'einreichen',
                popularqa : 'Beliebte Fragen und Antworten',
                browse_all_articles : 'Alle Artikel durchsuchen',
                noblogsfound : 'Keine Blogs gefunden.',
                updateaccount :  'Konto aktualisieren',
                image : 'Bild',
                username : 'Benutzername',
                nickname : 'Spitzname',
                email : 'Email',
                update : 'Aktualisieren',
                updatepassword : 'Passwort aktualisieren',
                currentpassword : 'Aktuelles Passwort',
                newpassword : 'Neues Passwort',
                change : 'Veränderung',
                recomndedevent : 'Empfohlene Veranstaltungen',
                newsarchive : 'Nachrichtenarchiv',
                ourcommunities : 'Unsere Gemeinschaften',
                downloadnow : 'Jetzt herunterladen',
                categories : 'Kategorien',
                yourwallet : 'Deine Brie ftasche',
                yourjwel : 'Dein Jwel',
                yourcoins : 'Deine Münzen',
                buynow : 'Jetzt kaufen ',
                ourstreams : 'Unsere Streams',
                addstream : 'Stream hinzufügen',
                all : 'Alle',
                English : 'Englisch',
                Arabic : 'Arabisch',
                Germany : 'Deutsch',
                China : 'Chinesisch',
                India : 'Indisch',
                French : 'Französisch',
                admin_dashboard : 'Admin-Dashboard',
                no_news_available : 'Keine Nachrichten verfügbar.',
                add_stream : 'Stream hinzufügen',
                title : 'Titel',
                url : 'URL',
                language : 'Sprache',
                select_language : 'Sprache auswählen',
                image : 'Bild',
                add : 'Hinzufügen',
                username : 'Benutzername',
                nickname : 'Spitzname',
                email : 'Email',
                ip : 'IP',
                active : 'Aktiv',
                actions : 'Aktionen',
                edit_user : 'Benutzer bearbeiten',
                created_at : 'Erstellt am',
                user_details : 'Benutzerdetails',
                users : 'Benutzer',
                admins : 'Admins',
                blogs : 'Blogs',
                charges : 'Gebühren',
                communities : 'Gemeinschaften',
                events : 'Veranstaltungen',
                add_admin : 'Admin hinzufügen',
                edit_admin : 'Admin bearbeiten',

            },
            china: {
                welcome: '欢迎',
                select_language: '选择语言',
                arabic : '阿拉伯语',
                english : '英语',
                german : '德语',
                china : '中文',
                french : '法语',
                india : '印地语',
                myaccount : '我的帐户',
                changepassword : '更改密码',
                logout : '登出',
                home : '家',
                news : '新闻',
                wallet : '钱包',
                streams : '流',
                support : '支持',
                report : '报告',
                help : '帮助',
                main : '主要',
                sendreport : '发送报告',
                subject : '学科',
                selectsubject : '选择学科',
                details : '细节',
                try_to_include_all_details : '尽量包含所有细节...',
                attachfile : '附加文件',
                cancel : '取消',
                submit : '提交',
                popularqa : '热门问答',
                browse_all_articles : '浏览所有文章',
                noblogsfound : '未找到博客。',
                updateaccount : '更新帐户',
                image : '图片',
                username : '用户名',
                nickname : '昵称',
                email : '电子邮件',
                update : '更新',
                updatepassword : '更新密码',
                currentpassword : '当前密码',
                newpassword : '新密码',
                change : '更改',
                recomndedevent : '推荐活动',
                newsarchive : '新闻档案',
                ourcommunities : '我们的社区',
                downloadnow : '立即下载',
                categories : '分类',
                yourwallet : '你的钱包',
                yourjwel : '你的珠宝',
                yourcoins : '你的硬币',
                buynow : '现在购买',
                ourstreams : '我们的流',
                addstream : '添加流',
                all : '所有',
                English : '英语',
                Arabic : '阿拉伯语',
                Germany : '德语',
                China : '中文',
                India : '印地语',
                French : '法语',
                admin_dashboard : '管理仪表板',
                no_news_available : '没有可用的新闻。',
                add_stream : '添加流',
                title : '标题',
                url : '网址',
                language : '语言',
                select_language : '选择语言',
                image : '图片',
                add : '加',
                username : '用户名',
                nickname : '昵称',
                email : '电子邮件',
                ip : 'IP',
                active : '活跃',
                actions : '动作',
                edit_user : '编辑用户',
                created_at : '创建于',
                user_details : '用户详细信息',
                users : '用户',
                admins : '管理员',
                blogs : '博客',
                charges : '费用',
                communities : '社区',
                events : '活动',
                add_admin : '添加管理员',
                edit_admin : '编辑管理员',
            },
            french: {
                welcome: 'Bienvenue',
                select_language: 'Choisir la langue',
                arabic : 'Arabe',
                english : 'Anglais',
                german : 'Allemand',
                china : 'Chinois',
                french : 'Français',
                india : 'Indien',
                myaccount : 'Mon compte',
                changepassword : 'Changer le mot de passe',
                logout : 'Se déconnecter',
                home : 'Accueil',
                news : 'Actualités',
                wallet : 'Portefeuille',
                streams : 'Ruisseaux',
                support : 'Soutien',
                report : 'Rapport',
                help : 'Aide',
                main : 'Principal',
                sendreport : 'Envoyer un rapport',
                subject : 'Sujet',
                selectsubject : 'Sélectionnez le sujet',
                details : 'Détails',
                try_to_include_all_details : 'Essayez d\'inclure tous les détails...',
                attachfile : 'Attacher un fichier',
                cancel : 'Annuler',
                submit : 'Soumettre',
                popularqa : 'Questions et réponses populaires',
                browse_all_articles : 'Parcourir tous les articles',
                noblogsfound : 'Aucun blog trouvé.',
                updateaccount : 'Mettre à jour le compte',
                image : 'Image',
                username : 'Nom d\'utilisateur',
                nickname : 'Surnom',
                email : 'Email',
                update : 'Mettre à jour',
                updatepassword : 'Mettre à jour le mot de passe',
                currentpassword : 'Mot de passe actuel',
                newpassword : 'Nouveau mot de passe',
                change : 'Changement',
                recomndedevent : 'Événements recommandés',
                newsarchive : 'Archives des nouvelles',
                ourcommunities : 'Nos communautés',
                downloadnow : 'Télécharger maintenant',
                categories : 'Catégories',
                yourwallet : 'Votre portefeuille',
                yourjwel : 'Votre Jwel',
                yourcoins : 'Vos pièces',
                buynow : 'Acheter maintenant',
                ourstreams : 'Nos flux',
                addstream : 'Ajouter un flux',
                all : 'Tout',
                English : 'Anglais',
                Arabic : 'Arabe',
                Germany : 'Allemand',
                China : 'Chinois',
                India : 'Indien',
                French : 'Français',
                admin_dashboard : 'Tableau de bord administrateur',
                no_news_available : 'Aucune nouvelle disponible.',
                add_stream : 'Ajouter un flux',
                title : 'Titre',
                url : 'URL',
                language : 'Langue',
                select_language : 'Choisir la langue',
                image : 'Image',
                add : 'Ajouter',
                username : 'Nom d\'utilisateur',
                nickname : 'Surnom',
                email : 'Email',
                ip : 'IP',
                active : 'Actif',
                actions : 'Actions',
                edit_user : 'Modifier l\'utilisateur',
                created_at : 'Créé à',
                user_details : 'Détails de l\'utilisateur',
                users : 'Utilisateurs',
                admins : 'Administrateurs',
                blogs : 'Blogs',
                charges : 'Frais',
                communities : 'Communautés',
                events : 'Événements',
                add_admin : 'Ajouter un administrateur',
                edit_admin : 'Modifier l\'administrateur',
            },
            india: {
                welcome: 'स्वागत है',
                select_language: 'भाषा चुनें',
                arabic : 'अरबी',
                english : 'अंग्रेज़ी',
                german : 'जर्मन',
                china : 'चीनी',
                french : 'फ्रांसीसी',
                india : 'भारतीय',
                myaccount : 'मेरा खाता',
                changepassword : 'पासवर्ड बदलें',
                logout : 'लॉग आउट',
                home : 'घर',
                news : 'समाचार',
                wallet : 'बटुआ',
                streams : 'धाराएँ',
                support : 'समर्थन',
                report : 'रिपोर्ट',
                help : 'मदद',
                main : 'मुख्य',
                sendreport : 'रिपोर्ट भेजें',
                subject : 'विषय',
                selectsubject : 'विषय चुनें',
                details : 'विवरण',
                try_to_include_all_details : 'सभी विवरण शामिल करने का प्रयास करें...',
                attachfile : 'फ़ाइल जोड़ें',
                cancel : 'रद्द करें',
                submit : 'प्रस्तुत',
                popularqa : 'लोकप्रिय प्रश्न और उत्तर',
                browse_all_articles : 'सभी लेख ब्राउज़ करें',
                noblogsfound : 'कोई ब्लॉग नहीं मिला।',
                updateaccount : 'खात अपडेट करें',
                image : 'छवि',
                username : 'उपयोगकर्ता नाम',
                nickname : 'उपनाम',
                email : 'ईमेल',
                update : 'अपडेट',
                updatepassword : 'पासवर्ड अपडेट करें',
                currentpassword : 'वर्तमान पासवर्ड',
                newpassword : 'नया पासवर्ड',
                change : 'परिवर्तन',
                recomndedevent : 'अनुशंसित घटनाएँ',
                newsarchive : 'समाचार संग्रह',
                ourcommunities : 'हमारी समुदाय',
                downloadnow : 'अभी डाउनलोड करें',
                categories : 'श्रेणियाँ',
                yourwallet : 'आपका बटुआ',
                yourjwel : 'आपकी ज्वेल',
                yourcoins : 'आपके सिक्के',
                buynow : 'अब खरीदें',
                ourstreams : 'हमारी धाराएँ',
                addstream : 'धारा जोड़ें',
                all : 'सब',
                English : 'अंग्रेज़ी',
                Arabic : 'अरबी',
                Germany : 'जर्मन',
                China : 'चीनी',
                India : 'भारतीय',
                French : 'फ्रांसीसी',
                admin_dashboard : 'व्यवस्थापक डैशबोर्ड',
                no_news_available : 'कोई खबर उपलब्ध नहीं है।',
                add_stream : 'धारा जोड़ें',
                title : 'शीर्षक',
                url : 'यूआरएल',
                language : 'भाषा',
                select_language : 'भाषा चुनें',
                image : 'छवि',
                add : 'जोड़ें',
                username : 'उपयोगकर्ता नाम',
                nickname : 'उपनाम',
                email : 'ईमेल',
                ip : 'आईपी',
                active : 'सक्रिय',
                actions : 'क्रियाएँ',
                edit_user : 'उपयोगकर्ता संपादित करें',
                created_at : 'पर बनाया गया',
                user_details : 'उपयोगकर्ता विवरण',
                users : 'उपयोगकर्ता',
                admins : 'व्यवस्थापक',
                blogs : 'ब्लॉग',
                charges : 'शुल्क',
                communities : 'समुदाय',
                events : 'घटनाएँ',
                add_admin : 'व्यवस्थापक जोड़ें',
                edit_admin : 'व्यवस्थापक संपादित करें',
            },
        };

        function translateContent(language) {
            const elementsToTranslate = document.querySelectorAll('[data-translate-key]');
            elementsToTranslate.forEach((element) => {
                const key = element.getAttribute('data-translate-key');
                if (translations[language] && translations[language][key]) {
                    element.innerText = translations[language][key];
                } else {
                    console.warn(`Translation for key "${key}" not found in "${language}" language.`);
                }
            });
        }

        const currentLanguageElement = document.querySelector('.uk-subnav-lang .lan');
        const languageDropdownItems = document.querySelectorAll('.uk-dropdown-nav .lan');

        function updateLanguageUI(language) {
            const selectedFlag = document.querySelector(`[data-lang="${language}"] img`);
            const selectedText = document.querySelector(`[data-lang="${language}"]`);

            if (currentLanguageElement && selectedFlag && selectedText) {
                currentLanguageElement.querySelector('img').src = selectedFlag.src;
                currentLanguageElement.querySelector('span').innerText = selectedText.textContent.trim();
            } else {
                console.warn(`Unable to find UI elements for language "${language}".`);
            }
        }

        const savedLanguage = localStorage.getItem('selectedLanguage') || 'english';
        translateContent(savedLanguage);
        updateLanguageUI(savedLanguage);

        languageDropdownItems.forEach((item) => {
            item.addEventListener('click', (event) => {
                event.preventDefault();
                const selectedLanguage = item.getAttribute('data-lang');
                if (translations[selectedLanguage]) {
                    localStorage.setItem('selectedLanguage', selectedLanguage);
                    translateContent(selectedLanguage);
                    updateLanguageUI(selectedLanguage);
                } else {
                    console.warn(`Translations for language "${selectedLanguage}" are not available.`);
                }
            });
        });
    });


</script>